apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

namespace: codelinesjs-dev

commonLabels:
  environment: dev

patches:
  - path: patches/server-patch.yaml

secretGenerator:
  - name: server-secret
    behavior: merge
    envs:
    - .env 

configMapGenerator:
  - name: server-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:3000 