apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codelinesjs-dev

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml

patchesStrategicMerge:
  - server-config-patch.yaml

commonLabels:
  environment: development

images:
  - name: ${DOCKER_REGISTRY}/codelinesjs-server
    newName: ${DOCKER_REGISTRY}/codelinesjs-server
    newTag: dev
  - name: ${DOCKER_REGISTRY}/codelinesjs-client
    newName: ${DOCKER_REGISTRY}/codelinesjs-client
    newTag: dev 