version: '3.8'

services:
  server:
    image: ${DOCKERHUB_USERNAME}/codelinesjs-server:main
    restart: always
    environment:
      - PORT=5001
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-adminpassword}@mongo:27017/codelinesjs?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      - JWT_COOKIE_EXPIRES_IN=86400000
      - FRONTEND_URL=${FRONTEND_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-1000}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HUGGING_FACE_API_KEY=${HUGGING_FACE_API_KEY}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    networks:
      - codelinesjs-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  codelinesjs-network:
    driver: bridge

volumes:
  mongo-data: 