# name: Docker Build and Push

# on:
#   push:
#     branches: [ main ]
#     tags: [ 'v*' ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
    
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
#     - name: Extract metadata for Docker
#       id: meta
#       uses: docker/metadata-action@v4
#       with:
#         images: ${{ secrets.DOCKER_HUB_USERNAME }}/codelines-api
#         tags: |
#           type=ref,event=branch
#           type=ref,event=tag
#           type=semver,pattern={{version}}
#           type=semver,pattern={{major}}.{{minor}}
#           type=sha,format=short
    
#     - name: Build and push Docker image
#       uses: docker/build-push-action@v4
#       with:
#         context: .
#         push: true
#         tags: ${{ steps.meta.outputs.tags }}
#         labels: ${{ steps.meta.outputs.labels }}
#         cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/codelines-api:buildcache
#         cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/codelines-api:buildcache,mode=max 