apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codelinesjs-ingress
  namespace: codelinesjs
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - codelinesjs.pl
    - www.codelinesjs.pl
    secretName: codelinesjs-tls
  rules:
  - host: codelinesjs.pl
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: server
            port:
              number: 5001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client
            port:
              number: 80
  - host: www.codelinesjs.pl
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: server
            port:
              number: 5001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client
            port:
              number: 80 