apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - server.yaml
  - ingress.yaml
  - secrets.yaml
  - network-policy.yaml
  - pdb.yaml

commonLabels:
  app: codelinesjs

namespace: codelinesjs 