apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongodb.yaml
  - server.yaml
  - client.yaml
  - ingress.yaml
  - cert-manager.yaml

commonLabels:
  app.kubernetes.io/part-of: codelinesjs
  app.kubernetes.io/managed-by: kustomize 