apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: server-pdb
  namespace: codelinesjs
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: codelinesjs
      component: server 