apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codelinesjs

resources:
  - ../../base

patchesStrategicMerge:
  - resources-patch.yaml
  - server-config-patch.yaml

commonLabels:
  environment: production

images:
  - name: ${DOCKER_REGISTRY}/codelinesjs-server
    newName: ${DOCKER_REGISTRY}/codelinesjs-server
    newTag: prod
  - name: ${DOCKER_REGISTRY}/codelinesjs-client
    newName: ${DOCKER_REGISTRY}/codelinesjs-client
    newTag: prod 