apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: codelinesjs

commonLabels:
  environment: prod

patches:
  - path: patches/server-patch.yaml

secretGenerator:
  - name: server-secret
    behavior: merge
    envs:
    - .server.env

configMapGenerator:
  - name: server-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - CORS_ORIGIN=https://codelinesjs.example.com 