apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "800m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: client
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m" 