name: Test i Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testy klienta
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Ustawienie Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
        
    - name: Instalacja zależności
      run: |
        cd client
        npm ci
        
    - name: Uruchomienie testów
      run: |
        cd client
        npm run test

  build-docker:
    name: Build obrazów Docker
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Logowanie do Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Ustawienie QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Ustawienie BuildX
      uses: docker/setup-buildx-action@v3
      
    - name: Build i push obrazu serwera
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.server
        push: true
        tags: |
          ol1mowski/codelinesjs-server:latest
          ol1mowski/codelinesjs-server:${{ github.sha }}
          
    - name: Build i push obrazu klienta
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.client.github
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ol1mowski/codelinesjs-client:latest
          ol1mowski/codelinesjs-client:${{ github.sha }}
          
    - name: Powiadomienie o zakończeniu
      if: always()
      run: |
        echo "Build zakończony - Sprawdź status zadań GitHub Actions" 