name: Test i Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Client tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Fix problem with case sensitivity in directory names
      run: |
        cd client/src
        if [ -d "Hooks" ] && [ ! -d "hooks" ]; then
          echo "Tworzenie dowiązania symbolicznego hooks -> Hooks"
          ln -s Hooks hooks
        fi
        
    - name: Install dependencies
      run: |
        cd client
        npm ci
        
    - name: Run tests in verbose mode
      run: |
        cd client
        NODE_ENV=test npm run test -- --reporter verbose
      env:
        CI: true

  build-docker:
    name: Build Docker images
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Fix problem with case sensitivity in directory names
      run: |
        cd client/src
        if [ -d "Hooks" ] && [ ! -d "hooks" ]; then
          echo "Tworzenie dowiązania symbolicznego hooks -> Hooks"
          ln -s Hooks hooks
        fi
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push server image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.server
        push: true
        tags: |
          ol1mowski187/codelinesjs-server:latest
          ol1mowski187/codelinesjs-server:${{ github.sha }}
          
    - name: Notify about completion
      if: always()
      run: |
        echo "Build completed - Check GitHub Actions status" 